### PR TITLE
Add `shell = True` to `run` options

### PR DESCRIPTION
**Pull request by Kerilk**
Per the manual:
If passing a single string, either shell must be True (see below) or else the string must simply name the program to be executed without specifying any arguments. https://docs.python.org/3/library/subprocess.html

Edit:

Now with Linux support.

### CODE REVIEW

**Comment by Timo654** [comment]
`shell = True` seems to have broken Windows support now.

XT1

**Comment by Kerilk** [comment]
Of course my bad, will create the path to the file using python os/file tools. Thanks for trying it.

**Comment by Kerilk** [comment]
Should be fixed, and now you should be able to run this tool from any directory previously it was assuming you were running from the tool root directory (as far as I understand)

**Comment by Timo654** [comment]
Seems good, thanks!

**Pull request merged**
